#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
mkdir "$dir/tags_lock" 2>/dev/null || exit 0
trap 'rmdir "$dir/tags_lock"; rm -f "$dir/$$.tags"' EXIT
git ls-files | grep -iv boost | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
